language: node_js
node_js:
  - "10"

dist: xenial
sudo: required
services:
  - xvfb

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - (npm install)

script:
  - (npm run lint)
  - (ng build --prod)